/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.training;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public Integer divide(int n1,int n2) {
        return n1/n2;
    }
}
